### ISSUE TITLE
bug: download breaks on song with unconventional characters

### ISSUE THREAD

**Issue by chiumax** [SwapnilSoni1999/spotify-dl#100]
**To Reproduce**
1. `spotifydl https://open.spotify.com/track/5XTePlyEtcOY5oRdJHNagB?si=89ba1218bdd94865`

**error logs**
```
PS D:\temp\music> spotifydl https://open.spotify.com/track/5XTePlyEtcOY5oRdJHNagB?si=9d596d9a89fd4cc7
ℹ Total Songs: 1
ℹ Saving: D:\temp\music\多想將一切做得完美 (電視劇《他們在畢業的前一天爆炸 二部曲》插曲) Frandé
ℹ Folder: 多想將一切做得完美 (電視劇《他們在畢業的前一天爆炸 二部曲》插曲) Frandé
ℹ 1/1 Song: 多想將一切做得完美 (電視劇《他們在畢業的前一天爆炸 二部曲》插曲) - Frandé
⠋ Downloading...Error: No video id found: TypeError: Cannot read property 'url' of undefined
    at Object.exports.getVideoID (C:\Users\Super\AppData\Roaming\nvm\v15.11.0\node_modules\spotify-dl\node_modules\ytdl-core\lib\url-utils.js:66:11)
    at Function.exports.<computed> [as getInfo] (C:\Users\Super\AppData\Roaming\nvm\v15.11.0\node_modules\spotify-dl\node_modules\ytdl-core\lib\info.js:471:29)
    at ytdl (C:\Users\Super\AppData\Roaming\nvm\v15.11.0\node_modules\spotify-dl\node_modules\ytdl-core\lib\index.js:19:8)
    at downloader (C:\Users\Super\AppData\Roaming\nvm\v15.11.0\node_modules\spotify-dl\lib\downloader.js:15:20)
    at downloadLoop (C:\Users\Super\AppData\Roaming\nvm\v15.11.0\node_modules\spotify-dl\cli.js:80:11)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async downloadSongList (C:\Users\Super\AppData\Roaming\nvm\v15.11.0\node_modules\spotify-dl\cli.js:111:3)
    at async run (C:\Users\Super\AppData\Roaming\nvm\v15.11.0\node_modules\spotify-dl\cli.js:129:9)
PS D:\temp\music> spotifydl -v
1.0.0
```

**Comment by phyzical** [comment]
this should be fixed by https://github.com/SwapnilSoni1999/spotify-dl/pull/98

**Comment by SwapnilSoni1999** [comment]
Please update to latest version and inform

**Comment by SwapnilSoni1999** [comment]
I've tested with the provided link and it works well with linux. No errors found. So closing the issue.
