### ISSUE TITLE
searching type error

### ISSUE THREAD

**Issue by thaynos** [SwapnilSoni1999/spotify-dl#104]
```
C:\Users\GUEST123>spotifydl https://open.spotify.com/playlist/6AveSaAdFrf2YVR8TU9kuD?si=21c1a8a445444e8a
- Searching…TypeError: Cannot read property 'id' of null
    at C:\Users\GUEST123\spotify-dl\lib\api.js:53:56
    at Array.map (<anonymous>)
    at Object.extractPlaylist (C:\Users\GUEST123\spotify-dl\lib\api.js:53:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async SpotifyExtractor.extractPlaylist (C:\Users\GUEST123\spotify-dl\util\get-songdata.js:53:12)
    at async SpotifyExtractor.getPlaylist (C:\Users\GUEST123\spotify-dl\util\get-songdata.js:38:12)
    at async run (C:\Users\GUEST123\spotify-dl\cli.js:134:11)
```

**Comment by phyzical** [comment]
hey @thaynos do you mind trying my branch? https://github.com/SwapnilSoni1999/spotify-dl/pull/102 and see if this issue is resolved

**Comment by thaynos** [comment]
how do i try it? and how do i allow that link in spotify dev?

**Comment by phyzical** [comment]
sure, 

for a unix system it would be
```
git clone https://github.com/phyzical/spotify-dl
git checkout feature/adding-logged-in-support
cd spotify-dl
npm install
npm link
```

**Comment by phyzical** [comment]
infact pr was just merged so please try the latest once a new version is pushed and see if the problem persists

**Comment by thaynos** [comment]
ok thx
