### ISSUE TITLE
Error: Promise Rejected with Value: 'http status: 429'

### ISSUE THREAD

**Issue by rsuchwani** [SwapnilSoni1999/spotify-dl#125]
I'm getting this error, no matter what I download (playlist, track, or album), it's always the same. Can someone please guide me to sort this issue?

$ sudo spotifydl "https://open.spotify.com/track/6RNDeRnWsRMjPdNVgupZCs?si=0fdbc024f2fb4043"
ℹ Generating new access token
ℹ Downloading: I Just Called To Say I Love You Stevie Wonder
ℹ Total Songs: 1
ℹ 1/1
Artist: Stevie Wonder
Album: At The Close Of A Century
Song: I Just Called To Say I Love You
Error: Promise rejected with value: 'http status: 429'
    at process.on.error (/root/spotify-dl/node_modules/hard-rejection/index.js:15:12)
    at process.emit (events.js:198:13)
    at processEmit [as emit] (/root/spotify-dl/node_modules/signal-exit/index.js:161:32)
    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
    at process._tickCallback (internal/process/next_tick.js:69:34)
$

**Comment by phyzical** [comment]
i started getting this also, i found that providing the cookies file similar to what is needed for youtube-dl fixed the issue

i will have a pr up later in the week to allow this functionality
