### ISSUE TITLE
i am userror 401 http st

### ISSUE THREAD

**Issue by mrut1688** [SwapnilSoni1999/spotify-dl#127]
PS C:\Users\pbyas>  spotify-dl https://open.spotify.com/track/6zaxxZxxjUJ0I3AYkzp2WA
Expected id of type album but found type https spotify:album:https://open.spotify.com/track/6zaxxZxxjUJ0I3AYkzp2WA
HTTP Error for GET to https://api.spotify.com/v1/albums///open.spotify.com/track/6zaxxZxxjUJ0I3AYkzp2WA returned 401 due to No token provided
Traceback (most recent call last):
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 245, in _internal_call
    response.raise_for_status()
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.spotify.com/v1/albums///open.spotify.com/track/6zaxxZxxjUJ0I3AYkzp2WA

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pbyas\AppData\Local\Programs\Python\Python39\Scripts\spotify-dl-script.py", line 33, in <module>
    sys.exit(load_entry_point('spotify-downloader==0.4.2', 'console_scripts', 'spotify-dl')())
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\app\app.py", line 44, in main
    album = sp.album(urn)
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 425, in album
    return self._get("albums/" + trid)
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 291, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 261, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 401, code:-1 - https://api.spotify.com/v1/albums///open.spotify.com/track/6zaxxZxxjUJ0I3AYkzp2WA:
 No token provided, reason: None
PS C:\Users\pbyas>  spotify-dl https://open.spotify.com/track/6zaxxZxxjUJ0I3AYkzp2WA
Expected id of type album but found type https spotify:album:https://open.spotify.com/track/6zaxxZxxjUJ0I3AYkzp2WA
HTTP Error for GET to https://api.spotify.com/v1/albums///open.spotify.com/track/6zaxxZxxjUJ0I3AYkzp2WA returned 401 due to No token provided
Traceback (most recent call last):
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 245, in _internal_call
    response.raise_for_status()
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.spotify.com/v1/albums///open.spotify.com/track/6zaxxZxxjUJ0I3AYkzp2WA

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pbyas\AppData\Local\Programs\Python\Python39\Scripts\spotify-dl-script.py", line 33, in <module>
    sys.exit(load_entry_point('spotify-downloader==0.4.2', 'console_scripts', 'spotify-dl')())
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\app\app.py", line 44, in main
    album = sp.album(urn)
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 425, in album
    return self._get("albums/" + trid)
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 291, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "C:\Users\pbyas\AppData\Roaming\Python\Python39\site-packages\spotipy\client.py", line 261, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 401, code:-1 - https://api.spotify.com/v1/albums///open.spotify.com/track/6zaxxZxxjUJ0I3AYkzp2WA:
 No token provided, reason: None``

**Comment by mrut1688** [comment]
its error i am getting while using it
can anyone help me out

**Comment by phyzical** [comment]
wrong repo? 
this is a node based solution not a python :)

**Comment by SwapnilSoni1999** [comment]
Wrong repo
