### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ZarBoy68** [SwapnilSoni1999/spotify-dl#131]
Error: ffmpeg version 2021-08-14-git-acd079843b-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57.  4.100 / 57.  4.100
  libavcodec     59.  4.101 / 59.  4.101
  libavformat    59.  4.101 / 59.  4.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  1.103 /  8.  1.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
C:\Users\nasho\Desktop\ПОЛЕЗНЫЕ УТИЛИТЫ\spotdl\ryo (supercell)\HATSUNE MIKU EXPO 2014 IN INDONESIA [Live]\こっち向いて Baby -MIKU EXPO 2014 in INDONESIA Live-.mp3: No such file or directory

    at ChildProcess.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\spotify-dl\node_modules\ffmetadata\index.js:89:16)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:1001:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)

**Comment by phyzical** [comment]
hey just guessing based on the folder name are you sure this is the right repo? you might be after this one https://github.com/spotDL/spotify-downloader

**Comment by phyzical** [comment]
@ZarBoy68 thanks for the issue, do you mind giving more information i.e the full command you ran so we cant try and replicate?
