### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by yousef-0000** [SwapnilSoni1999/spotify-dl#135]
my problem 
*******************************************************************************************************************************************
xenso@xenso-Lenovo-Z50-70:~$ spotifydl https://open.spotify.com/track/0HpoU9wzx6lhK1jIa6cVU3?si=3ca4ca255605449e
/home/xenso/spotify-dl/cli.js:17
import { startup } from './lib/setup.js';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
********************************************************************************************
npm version 6.14.4
node version 10.19.0
op= enso linux(ubuntu)

**Comment by micheeell** [comment]
Same error here:
npm version 7.23.0
node 10.19.0
operating system: mint 20.2 Cinnamon
