### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME

### ISSUE THREAD

**Issue by retrogradeorbit** [SwapnilSoni1999/spotify-dl#146]
**Describe the bug**
Program exits with error: ERR_UNSUPPORTED_ESM_URL_SCHEME

```
$ ~/.nvm/versions/node/v12.18.2/bin/spotifydl
(node:17350) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:727:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:46:40)
    at link (internal/modules/esm/module_job.js:45:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

**To Reproduce**
1. install programme with `npm install -g spotify-dl`
2. execute the program

**Expected behavior**
The program should run

**Desktop (please complete the following information):**
 - OS: Ubuntu 18 Linux

**Comment by 2V3EvG4LMJFdRe** [comment]
Same on macOS High Sierra.

**Comment by phyzical** [comment]
hey @retrogradeorbit  and @2V3EvG4LMJFdRe 

Thanks for the issue, i think the issue may be the node version? its working for myself on node 14.

But i have posted a pr to update the readme to help others.

Feel free to let me know if node 14 does not fix the issue.

**Comment by 2V3EvG4LMJFdRe** [comment]
Thanks for taking a look at it. I'm not sure what has changed, not really familiar with what node is or how it installed/updated. I've removed spotifydl and installed from 0 like this:

```
Last login: Fri Jan 21 20:11:46 on ttys000
2V3EvG4LMJFdRes-iMac:~ 2V3EvG4LMJFdRe$ git clone https://github.com/SwapnilSoni1999/spotify-dl
Cloning into 'spotify-dl'...
remote: Enumerating objects: 1266, done.
remote: Counting objects: 100% (270/270), done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 1266 (delta 194), reused 206 (delta 161), pack-reused 996
Receiving objects: 100% (1266/1266), 25.33 MiB | 11.12 MiB/s, done.
Resolving deltas: 100% (774/774), done.
2V3EvG4LMJFdRes-iMac:~ 2V3EvG4LMJFdRe$ cd spotify-dl
2V3EvG4LMJFdRes-iMac:spotify-dl 2V3EvG4LMJFdRe$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> puppeteer@8.0.0 install /Users/2V3EvG4LMJFdRe/spotify-dl/node_modules/puppeteer
> node install.js

Downloading Chromium r856583 - 111.1 Mb [====================] 100% 0.0s 
Chromium (856583) downloaded to /Users/2V3EvG4LMJFdRe/spotify-dl/node_modules/puppeteer/.local-chromium/mac-856583
added 658 packages from 436 contributors and audited 658 packages in 21.972s

124 packages are looking for funding
  run `npm fund` for details

found 11 vulnerabilities (1 low, 5 moderate, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
2V3EvG4LMJFdRes-iMac:spotify-dl 2V3EvG4LMJFdRe$ npm audit fix
npm WARN eslint-import-resolver-webpack@0.13.2 requires a peer of webpack@>=1.11.0 but none is installed. You must install peer dependencies yourself.

updated 3 packages in 3.659s

124 packages are looking for funding
  run `npm fund` for details

fixed 2 of 11 vulnerabilities in 658 scanned packages
  9 vulnerabilities required manual review and could not be updated
2V3EvG4LMJFdRes-iMac:spotify-dl 2V3EvG4LMJFdRe$ npm link
npm WARN eslint-import-resolver-webpack@0.13.2 requires a peer of webpack@>=1.11.0 but none is installed. You must install peer dependencies yourself.

audited 658 packages in 4.882s

124 packages are looking for funding
  run `npm fund` for details

found 9 vulnerabilities (1 low, 4 moderate, 3 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
/Users/2V3EvG4LMJFdRe/n/bin/spotifydl -> /Users/2V3EvG4LMJFdRe/n/lib/node_modules/spotify-dl/cli.js
/Users/2V3EvG4LMJFdRe/n/lib/node_modules/spotify-dl -> /Users/2V3EvG4LMJFdRe/spotify-dl
2V3EvG4LMJFdRes-iMac:spotify-dl 2V3EvG4LMJFdRe$ spotifydl
(node:20877) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:698:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
2V3EvG4LMJFdRes-iMac:spotify-dl 2V3EvG4LMJFdRe$ 
```

**Comment by phyzical** [comment]
hey @2V3EvG4LMJFdRe what is the output for `node --version`

**Comment by 2V3EvG4LMJFdRe** [comment]
v17.4.0 @phyzical

**Comment by phyzical** [comment]
@2V3EvG4LMJFdRe thanks, i would suggest just reinstalling your node if your not super familiar with how it all works, another options is to use something like  nvm (https://github.com/nvm-sh/nvm)
