### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by TarushS** [SwapnilSoni1999/spotify-dl#15]
ℹ 6. Song: Flexem - Ohmie
⠙ Downloading...events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Input stream error: Too many redirects
    at PassThrough.<anonymous> (/usr/local/lib/node_modules/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:452:34)
    at emitOne (events.js:121:20)
    at PassThrough.emit (events.js:211:7)
    at PassThrough.req.prependListener (/usr/local/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/index.js:131:14)
    at emitOne (events.js:121:20)
    at PassThrough.emit (events.js:211:7)
    at onError (/usr/local/lib/node_modules/spotify-dl/node_modules/m3u8stream/lib/index.js:64:12)
    at onQueuedEnd (/usr/local/lib/node_modules/spotify-dl/node_modules/m3u8stream/lib/index.js:81:7)
    at PassThrough._worker (/usr/local/lib/node_modules/spotify-dl/node_modules/m3u8stream/lib/queue.js:43:23)
    at emitOne (events.js:116:13)

**Comment by SwapnilSoni1999** [comment]
can you share that playlist url?

**Comment by TarushS** [comment]
https://open.spotify.com/playlist/2GlfPm1ydSwidF0RYUeais

**Comment by SwapnilSoni1999** [comment]
check if it works with a vpn or not or proxy it should work as mentioned at #18
