### ISSUE TITLE
Problems with downloads

### ISSUE THREAD

**Issue by eioo** [SwapnilSoni1999/spotify-dl#16]
Tried to download this track: https://open.spotify.com/track/6Ey0OR1AwumO2jgYnNo0MK?si=D4va3fMdRVqmcdl0bOpMrQ
(Don't mind the song lol)

Greeted with this error:
```
i Saving Song to: C:\Users\khirv\Heitterit - LAZZI.mp3

√ Song: Heitterit - LAZZI
- Downloading...Something went wrong!
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type object
    at Url.parse (url.js:152:11)
    at Object.urlParse [as parse] (url.js:146:13)
    at Object.exports.getURLVideoID (C:\Users\khirv\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\ytdl-core\lib\util.js:273:22)
    at Object.exports.getVideoID (C:\Users\khirv\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\ytdl-core\lib\util.js:304:20)
    at Function.exports.(anonymous function) [as getInfo] (C:\Users\khirv\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\ytdl-core\lib\info.js:362:21)
    at ytdl (C:\Users\khirv\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\ytdl-core\lib\index.js:17:8)
    at downloader (C:\Users\khirv\AppData\Roaming\npm\node_modules\spotify-dl\lib\downloader.js:14:20)
    at C:\Users\khirv\AppData\Roaming\npm\node_modules\spotify-dl\cli.js:98:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Also, I tried to download this song: https://open.spotify.com/track/7bqpbw3e3TeJwgYWRYtE1K?si=eyFynJ5eReKff4Qr5HOMyQ

It says the download is 3401.37MB in size, the song in itself is like 1:15 long, here's the output:
```
i Saving Song to: C:\Users\khirv\Heroes Of Might And Magic III Snowland - buskerflutist.mp3

√ Song: Heroes Of Might And Magic III Snowland - buskerflutist
/ Downloading 21.09MB of 3401.37MB
```

(Obviously skipped the download)

**Comment by SwapnilSoni1999** [comment]
because it uses youtube-dl it might be some issues with that though cant help with youtube's seo and for that error try pasting the url with quotes
