### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by ObsidianOne666** [SwapnilSoni1999/spotify-dl#17]
Hey , i cant download anything with this.Can you help ? 

```
INFO: Could not find files for the given pattern(s).
child_process.js:669
    throw err;
    ^

> Error: Command failed: where ffmpeg
> INFO: Could not find files for the given pattern(s).
> 
>     at checkExecSyncError (child_process.js:629:11)
>     at execSync (child_process.js:666:13)
>     at Object.ffmpeg (C:\Users\EXCALIBUR\AppData\Roaming\npm\node_modules\spotify-dl\lib\setup.js:8:38)
>     at Object.<anonymous> (C:\Users\EXCALIBUR\AppData\Roaming\npm\node_modules\spotify-dl\cli.js:16:7)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

**Comment by SwapnilSoni1999** [comment]
you need to get ffmpeg
