### ISSUE TITLE
If you try download a Album/playlist with spaces it creates a corrupted folder

### ISSUE THREAD

**Issue by xboxnoob** [SwapnilSoni1999/spotify-dl#19]
The folder it creates only is visible to directory listings but if you try delete it says that this folder doesnt exist
I only tested this on windows i will get a linux machine up later and test this

**Comment by xboxnoob** [comment]
`events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: D:\Utamonogatari Special Edition (Original Soundtrack) - Aniplex Inc.\Staple Stable - MONOGATARI Series.mp3: No such file or directory

    at ChildProcess.<anonymous> (C:\Users\conor\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Emitted 'error' event at:
    at emitEnd (C:\Users\conor\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at endCB (C:\Users\conor\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:544:13)
    at handleExit (C:\Users\conor\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:170:11)
    at ChildProcess.<anonymous> (C:\Users\conor\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:182:11)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)`
here is the logs

**Comment by SwapnilSoni1999** [comment]
can you share the spotify url please
