### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by AnasGhareib** [SwapnilSoni1999/spotify-dl#21]
module.js:549
    throw err;
    ^

Error: Cannot find module 'm3u8stream/lib/parse-time'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/elanoos/spotify-dl/node_modules/ytdl-core/lib/info-extras.js:5:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by wjkhoo96** [comment]
Here's the solution that I found
https://stackoverflow.com/questions/58965713/cannot-find-module-m3u8stream-lib-parse-time

**Comment by Wizard451345** [comment]
Is this the same thing right?


i ©
internal/modules/cjs/loader.js:798
    throw err;
    ^

Error: Cannot find module 'm3u8stream/lib/parse-time'
Require stack:
- /data/data/com.termux/files/usr/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/info-extras.js
- /data/data/com.termux/files/usr/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/info.js
- /data/data/com.termux/files/usr/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/index.js
- /data/data/com.termux/files/usr/lib/node_modules/spotify-dl/lib/downloader.js
- /data/data/com.termux/files/usr/lib/node_modules/spotify-dl/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/info-extras.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Module.require (internal/modules/cjs/loader.js:850:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/data/com.termux/files/usr/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/info-extras.js',
    '/data/data/com.termux/files/usr/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/info.js',
    '/data/data/com.termux/files/usr/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/index.js',
    '/data/data/com.termux/files/usr/lib/node_modules/spotify-dl/lib/downloader.js',
    '/data/data/com.termux/files/usr/lib/node_modules/spotify-dl/cli.js'
  ]
}
Press any key to exit...

**Comment by SwapnilSoni1999** [comment]
Fixed on v0.1.6
