### ISSUE TITLE
"TypeError: Cannot read property 'id' of null" before downloading

### ISSUE THREAD

**Issue by Pete1976** [SwapnilSoni1999/spotify-dl#227]
**Describe the bug**
TypeError: Cannot read property 'id' of null

**To Reproduce**
spotifydl https://open.spotify.com/intl-de/track/1leXj0r8M0dMFNWbRxq2Xe

**Expected behavior**
download without error

**Output**
ℹ Starting processing of song (https://open.spotify.com/intl-de/track/1leXj0r8M0dMFNWbRxq2Xe)
ℹ extracting track set 1/1
ℹ Generating new access token
TypeError: Cannot read property 'id' of null
    at file:///usr/local/lib/node_modules/spotify-dl/lib/api.js:225:34
    at Array.find (<anonymous>)
    at parseTrack (file:///usr/local/lib/node_modules/spotify-dl/lib/api.js:224:38)
    at file:///usr/local/lib/node_modules/spotify-dl/lib/api.js:221:39
    at Array.map (<anonymous>)
    at extractTracks (file:///usr/local/lib/node_modules/spotify-dl/lib/api.js:221:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getTrack (file:///usr/local/lib/node_modules/spotify-dl/util/get-songdata.js:8:11)
    at async run (file:///usr/local/lib/node_modules/spotify-dl/util/runner.js:150:23)

**Additional context**
I tried to find a fix but was not able.

**Comment by phyzical** [comment]
@Pete1976 thanks for the reort, was able to reproduce and has been fixed in master
