### ISSUE TITLE
Throws error

### ISSUE THREAD

**Issue by Riku32** [SwapnilSoni1999/spotify-dl#24]
| Downloading...events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: Input stream error: This video is unavailable
    at PassThrough.<anonymous> (D:\Downloads\Song\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:452:34)
    at PassThrough.emit (events.js:210:5)
    at D:\Downloads\Song\spotify-dl\node_modules\ytdl-core\lib\index.js:19:14
    at D:\Downloads\Song\spotify-dl\node_modules\ytdl-core\lib\info.js:370:25
    at D:\Downloads\Song\spotify-dl\node_modules\ytdl-core\lib\info.js:255:7
    at D:\Downloads\Song\spotify-dl\node_modules\ytdl-core\lib\info.js:373:9
    at D:\Downloads\Song\spotify-dl\node_modules\ytdl-core\lib\info.js:198:5
    at PassThrough.<anonymous> (D:\Downloads\Song\spotify-dl\node_modules\miniget\dist\index.js:196:32)
    at PassThrough.emit (events.js:210:5)
    at endReadableNT (_stream_readable.js:1183:12)
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (D:\Downloads\Song\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at PassThrough.<anonymous> (D:\Downloads\Song\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:454:15)
    at PassThrough.emit (events.js:210:5)
    [... lines matching original stack trace ...]
    at PassThrough.emit (events.js:210:5) {
  inputStreamError: Error: This video is unavailable
      at D:\Downloads\Song\spotify-dl\node_modules\ytdl-core\lib\info.js:255:16
      at D:\Downloads\Song\spotify-dl\node_modules\ytdl-core\lib\info.js:373:9
      at D:\Downloads\Song\spotify-dl\node_modules\ytdl-core\lib\info.js:198:5
      at PassThrough.<anonymous> (D:\Downloads\Song\spotify-dl\node_modules\miniget\dist\index.js:196:32)
      at PassThrough.emit (events.js:210:5)
      at endReadableNT (_stream_readable.js:1183:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
}

**Comment by SwapnilSoni1999** [comment]
try with vpn

**Comment by SwapnilSoni1999** [comment]
fixed with release 0.1.8

https://github.com/SwapnilSoni1999/spotify-dl/releases/tag/0.1.8
