### ISSUE TITLE
Error in playlist link

### ISSUE THREAD

**Issue by marcdubois71450** [SwapnilSoni1999/spotify-dl#25]
Hello,
I am having a problem with your library, the application is blocking 30 th music in a playlist, here is the error. But I don't understand the error ?

```
✔ Metadata Merged!
ℹ 30. Song: Cellophané - Rim'K
- Downloading...
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type object
    at Url.parse (url.js:154:11)
    at Object.urlParse [as parse] (url.js:148:13)
    at Object.exports.getURLVideoID (/usr/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/util.js:265:22)
    at Object.exports.getVideoID (/usr/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/util.js:298:20)
    at Function.exports.(anonymous function) [as getInfo] (/usr/lib/node_modules/spotify-dl/node_modules/ytdl-core/li
b/info.js:335:17)
    at ytdl (/usr/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/index.js:17:8)
    at downloader (/usr/lib/node_modules/spotify-dl/lib/downloader.js:14:20)
    at downloadLoop (/usr/lib/node_modules/spotify-dl/cli.js:156:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Voici le lien de la playlist : https://open.spotify.com/playlist/4tYmq6H1dowHunEZ8lQJTO?si=hY1IgOrGQJK7nXoU7Y8vYw 

thank you so much

**Comment by SwapnilSoni1999** [comment]
it could be that the music  which is on youtube, cant be accessed via your ip 
Try with any vpn and inform please.

**Comment by SwapnilSoni1999** [comment]
closed because of inactivity
