### ISSUE TITLE
`spotifydl` Fails with 403 Error When Generating New Access Token

### ISSUE THREAD

**Issue by Hx-Regex** [SwapnilSoni1999/spotify-dl#254]
# Issue: `spotifydl` Fails with 403 Error When Generating New Access Token

## Description

I am encountering a `403` error when trying to use the `spotifydl` . The tool attempts to generate a new access token, but the request fails with a `403` status code.

```
ℹ Starting processing of song (https://open.spotify.com/track/427vwwlrlHy0JZPVt8rzYS)
ℹ extracting track set 1/1
ℹ Generating new access token
AxiosError: Request failed with status code 403
    at settle (file:///C:/Users/hexga/AppData/Roaming/npm/node_modules/@swapnilsoni1999/spotify-dl/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///C:/Users/hexga/AppData/Roaming/npm/node_modules/@swapnilsoni1999/spotify-dl/node_modules/axios/lib/adapters/http.js:589:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (file:///C:/Users/hexga/AppData/Roaming/npm/node_modules/@swapnilsoni1999/spotify-dl/node_modules/axios/lib/core/Axios.js:45:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async checkVersion (file:///C:/Users/hexga/AppData/Roaming/npm/node_modules/@swapnilsoni1999/spotify-dl/util/version-checker.js:5:15)
    ```

**Comment by phyzical** [comment]
@Hx-Regex is this the new install location or the old one? https://github.com/SwapnilSoni1999/spotify-dl?tab=readme-ov-file#npm

**Comment by Hx-Regex** [comment]
i used the new one

**Comment by phyzical** [comment]
oh actually, its github throttling it looks like. ill just make the version check a soft error

**Comment by phyzical** [comment]
@Hx-Regex lmk if  `@swapnilsoni1999/spotify-dl@1.2.1` resolves the issue
