### ISSUE TITLE
Getting error while downloading a playlist with "/" character.

### ISSUE THREAD

**Issue by suvmpr** [SwapnilSoni1999/spotify-dl#43]
```
⠋ Searching…⠙ Searching…⠹ Searching…ℹ Total Songs: 78
ℹ Saving Playlist: /content/drive/My Drive/anime-songs/Peace and Sorrows (Anime/Misc) - Jadd Lee
✖ Something went wrong!
{ Error: ENOENT: no such file or directory, mkdir '/content/drive/My Drive/anime-songs/Peace and Sorrows (Anime/Misc) - Jadd Lee'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.read (/usr/local/lib/node_modules/spotify-dl/lib/cache.js:19:16)
    at /usr/local/lib/node_modules/spotify-dl/cli.js:109:38
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/content/drive/My Drive/anime-songs/Peace and Sorrows (Anime/Misc) - Jadd Lee' }

```
**getting error , evrytime downloading a playlist with ''/"
please fix.**

**Comment by SwapnilSoni1999** [comment]
Will look for it thanks for informing
