### ISSUE TITLE
The "url" argument must be of type string. Received an instance of TypeError

### ISSUE THREAD

**Issue by Pawiczekk** [SwapnilSoni1999/spotify-dl#50]
I was trying to download a playlist, but this song kept throwing this error, even when downloading it separately: https://open.spotify.com/track/4IxwUN8Q34OLznTomcg6LL
Using version 0.4.3 (for some reason it says that an update is available, but package.json in this repo has the same version, already tried reinstalling)
```
PS C:\Users\X\Desktop\test> spotifydl "https://open.spotify.com/track/4IxwUN8Q34OLznTomcg6LL"                                                         ========Update Available========
Use npm install -g spotify-dl
to update the package.
================================
i Saving Song to: C:\Users\X\Desktop\test\Agunamonita -202- - Saitama Saisyu Heiki.mp3
√ Song: Agunamonita -202- - Saitama Saisyu Heiki
× Something went wrong!
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of TypeError
    at validateString (internal/validators.js:117:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at Object.exports.getURLVideoID (C:\Users\X\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\ytdl-core\lib\util.js:252:22)
    at Object.exports.getVideoID (C:\Users\X\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\ytdl-core\lib\util.js:285:20)
    at Function.exports.<computed> [as getInfo] (C:\Users\Pawii\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\ytdl-core\lib\info.js:320:19)
    at ytdl (C:\Users\X\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\ytdl-core\lib\index.js:17:8)
    at downloader (C:\Users\X\AppData\Roaming\npm\node_modules\spotify-dl\lib\downloader.js:14:20)
    at C:\Users\X\AppData\Roaming\npm\node_modules\spotify-dl\cli.js:96:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
PS C:\Users\X\Desktop\test>
```
(replaced username with X)

**Comment by SwapnilSoni1999** [comment]
Sorry it was my mistake while pushing tags can you please check again by installing again
```sh
npm install -g spotify-dl
```

**Comment by Pawiczekk** [comment]
Update notification is gone, but this song still throws the same error

**Comment by SwapnilSoni1999** [comment]
please update to version `0.4.4` and check

**Comment by Pawiczekk** [comment]
Fixed, thanks.
