### ISSUE TITLE
FFMPEG Invalid Argument

### ISSUE THREAD

**Issue by YV31** [SwapnilSoni1999/spotify-dl#52]
Trying to download: https://open.spotify.com/album/4GGazqHvuKwxBjWLFaJkDL

Probably a issue on parsing spaces. Should be replaced with "\ ".

*Log:*
```
ℹ Total Songs: 12
ℹ Saving Album: Justice/Justice - Ed Banger Records
ℹ 1. Song: Genesis - Justice
⠋ Downloading 1.13MB of 3.77MB
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: /home/<home>/Music/Justice/Justice - Ed Banger Records: Invalid argument

    at ChildProcess.<anonymous> (<path-to-sptifydl>/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Emitted 'error' event at:
    at emitEnd (<path-to-sptifydl>/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at endCB (<path-to-sptifydl>spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:544:13)
    at handleExit (<path-to-sptifydl>/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:170:11)
    at Socket.<anonymous> (<path-to-sptifydl>/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:197:11)
    at Socket.emit (events.js:203:15)
    at Pipe._handle.close (net.js:607:12)
```
*Note: Replace \<path-to-sptifydl\> with the location were spotify-dl is cloned.*

**Comment by user747** [comment]
`z@x:~/Downloads$ spotifydl https://open.spotify.com/album/1fvWYcbjuycyHpzNPH1Vfk
ℹ Total Songs: 11
ℹ Saving Album: /home/z/Downloads/10,000 Days - RCA Records Label
ℹ 1. Song: Vicarious - TOOL
⠼ Downloading...events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: /home/z/Downloads/10,000 Days - RCA Records Label: Invalid argument

    at ChildProcess.<anonymous> (/home/z/Downloads/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (/home/z/Downloads/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at endCB (/home/z/Downloads/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:544:13)
    at handleExit (/home/z/Downloads/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:170:11)
    at ChildProcess.<anonymous> (/home/z/Downloads/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:182:11)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
`

**Comment by SwapnilSoni1999** [comment]
If you found the solution then please mention in replies.
