### ISSUE TITLE
Error while Downloading

### ISSUE THREAD

**Issue by Prizrak-X** [SwapnilSoni1999/spotify-dl#55]
While trying to download a playlist, this is popping up consistently. OS- Windows 10. 

Downloading...Error: Input stream error: Error parsing info: Unable to retrieve video metadata
    at PassThrough.<anonymous> (C:\Users\prizrak\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:452:34)
    at PassThrough.emit (events.js:315:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Input stream error: Too many redirects
    at PassThrough.<anonymous> (C:\Users\prizrak\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:452:34)
    at PassThrough.emit (events.js:327:22)
    at PassThrough.emit (events.js:327:22)
    at onError (C:\Users\prizrak\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\m3u8stream\dist\index.js:67:16)
    at onQueuedEnd (C:\Users\prizrak\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\m3u8stream\dist\index.js:82:13)
    at PassThrough.<anonymous> (C:\Users\prizrak\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\m3u8stream\dist\queue.js:39:17)
    at PassThrough.emit (events.js:315:20)
    at ClientRequest.<anonymous> (C:\Users\prizrak\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\m3u8stream\node_modules\miniget\dist\index.js:129:28)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (C:\Users\prizrak\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at PassThrough.<anonymous> (C:\Users\prizrak\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:454:15)
    at PassThrough.emit (events.js:327:22)
    [... lines matching original stack trace ...]
    at Object.onceWrapper (events.js:422:26) {
  inputStreamError: Error: Too many redirects
      at ClientRequest.<anonymous> (C:\Users\prizrak\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\m3u8stream\node_modules\miniget\dist\index.js:129:42)
      at Object.onceWrapper (events.js:422:26)
      at ClientRequest.emit (events.js:315:20)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
      at TLSSocket.socketOnData (_http_client.js:509:22)
      at TLSSocket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:284:9)
      at TLSSocket.Readable.push (_stream_readable.js:223:10)

**Comment by WiktorG** [comment]
Can you test it on my forked repo? :) 
[Here it is!](https://github.com/WiktorG/spotify-dl)

I tried to fix those errors and it seems to work. If it does for you could you leave a comment in pull request so that the author will have proof before merging? 😁

[Pull request](https://github.com/SwapnilSoni1999/spotify-dl/pull/53)

**Comment by Prizrak-X** [comment]
@WiktorG   Downloading...Error: Input stream error: Could not find player config
    at PassThrough.<anonymous> (C:\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:452:34)
    at PassThrough.emit (events.js:315:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

The same issue, unfortunately :(

**Comment by WiktorG** [comment]
@Prizrak-X could you link me the playlist you're trying to download? :D

**Comment by Prizrak-X** [comment]
@WiktorG https://open.spotify.com/playlist/7kUtEP7LMjwmTNubP2RGOM

**Comment by WiktorG** [comment]
I'll check it when I have more time :)

**Comment by WiktorG** [comment]
@Prizrak-X one more question :D I see this has a lot of songs - is there any specific song that it stops on or it happens randomly

**Comment by Prizrak-X** [comment]
@WiktorG random

**Comment by SwapnilSoni1999** [comment]
Please check on updated version 
```npm install -g spotify-dl``` and report if any issue appears. 
Close if issue solved. 
Thanks.

**Comment by KoryJCampbell** [comment]
i'm having the same issue, this isn't working for me either

**Comment by SwapnilSoni1999** [comment]
@KoryJCampbell are you having ffmpeg installed and added to environment path ?

**Comment by akkim3** [comment]
I have ffmpeg installed and I'm having the same issue on MacOS. This is surprising since the script had been working last week without any issues. 

This is my error
`Downloading...Error: Input stream error: Error parsing info: Unable to retrieve video metadata
    at PassThrough.<anonymous> (/usr/local/lib/node_modules/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:452:34)
    at PassThrough.emit (events.js:315:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`

**Comment by RyanCccc** [comment]
Same issue here. Worked few days ago.
`
Downloading...Error: Error parsing info: Unable to retrieve video metadata
    at getWatchPage (/usr/local/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/info.js:75:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async exports.getBasicInfo (/usr/local/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/info.js:84:22)
    at async Map.getOrSet (/usr/local/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/cache.js:24:19)
    at async exports.getInfo (/usr/local/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/info.js:226:14)
    at async Map.getOrSet (/usr/local/lib/node_modules/spotify-dl/node_modules/ytdl-core/lib/cache.js:24:19)
`

**Comment by SwapnilSoni1999** [comment]
please check on latest release

**Comment by Prizrak-X** [comment]
> please check on the latest release

All issues have been fixed, I'm closing this issue. Thank you @SwapnilSoni1999
