### ISSUE TITLE
Error when running downloader

### ISSUE THREAD

**Issue by BaaBaaBruh** [SwapnilSoni1999/spotify-dl#6]
Hi, when downloading any song, I get this error:

TypeError: Cannot read property 'length' of undefined
    at PassThrough.download.on (C:\Users\[username]\spotify-dl\lib\downloader.js:30:27)
    at emitNone (events.js:111:20)
    at PassThrough.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

It shows up after the "downloading" has finished.

I've used these songs:
https://open.spotify.com/track/1T5MCAhOH1dtFsYXV627jh?si=jHy4cjfEQ3WNARCPQNTtGw
https://open.spotify.com/track/4mOPVJGfWXH0wPFA6xeRDz?si=mRY7X4tpRZaWcZS7dHfxfQ

**Comment by SwapnilSoni1999** [comment]
You need to remove queries from the link 
Which are `?si=stuffhere`
I'll add a filter to clean it byself

**Comment by pojntfx** [comment]
@SwapnilSoni1999 This seams to happen even with the newest version right now.

**Comment by SwapnilSoni1999** [comment]
@pojntfx can you paste logs please. Thanks

**Comment by pojntfx** [comment]
@SwapnilSoni1999 Sure! The issue happens with the following commands, for example:

```bash
% spotifydl "https://open.spotify.com/playlist/37i9dQZF1DX0AMssoUKCz7?si=_HhhCM2gSD69XaThKvwJgQ"
✖ Something went wrong!
TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/spotify-dl/lib/api.js:61:47
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Spotifye.extrPlaylist (/usr/local/lib/node_modules/spotify-dl/util/get-songdata.js:39:23)
    at async /usr/local/lib/node_modules/spotify-dl/cli.js:103:22
% spotifydl "https://open.spotify.com/playlist/37i9dQZF1DX0AMssoUKCz7?si=_HhhCM2gSD69XaThKvwJgQ" -o .
✖ Something went wrong!
TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/spotify-dl/lib/api.js:61:47
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Spotifye.extrPlaylist (/usr/local/lib/node_modules/spotify-dl/util/get-songdata.js:39:23)
    at async /usr/local/lib/node_modules/spotify-dl/cli.js:103:22
% spotifydl "https://open.spotify.com/playlist/37i9dQZF1DX0AMssoUKCz7" -o .                          
ℹ Total Songs: 200
ℹ Saving Playlist: Tropical House - Spotify
ℹ 1. Song: Silverskin - Sam Feldt
⠙ Downloading...^C%
```
