### ISSUE TITLE
Error: Input stream error: Error parsing info: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by Vardaan6189** [SwapnilSoni1999/spotify-dl#61]
Heyy THANKS FOR YOUR PROJECT !!!

But there is an error which i m facing 

This is the link for the song i am trying to download https://open.spotify.com/track/1G3u6h9MfeoAZYVbPTptbD?si=-4OCuxBTTVKl0cyK3OUb6A

But i get this error 

```
spotifydl -o /storage/emulated/0/ https://open.spotify.com/track/1G3u6h9MfeoAZYVbPTptbD?si=yuQCmt13R8KRxj6-roKPJQ

ℹ Saving Song to: /storage/emulated/0/Grief and Sorrow - DoctorNoSense.mp3
✔ Song: Grief and Sorrow - DoctorNoSense
⠋ Downloading...Error: Input stream error: Error parsing info: Unable to retrieve video metadata
    at PassThrough.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:452:34)
    at PassThrough.emit (events.js:315:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

Hope you will look knto the natter as soon as possible 🙂

**Comment by techie2000** [comment]
I have recreated this issue.
Install was done via npm. ffmpeg is installed. Running on Ubuntu 20.04

**Comment by pascal48** [comment]
I can also replicate, I have ffmpeg-4.3.1-11 installed.

Download source: https://open.spotify.com/track/2CZnuQBGvGryfY2hDAzH8x?si=fmgCVHDCS9KmmtjPZyzxzg

Output:
 

```
ℹ Saving Song to: /home/jakeb/Downloads/Detached - Emil Rottmayer.mp3
✔ Song: Detached - Emil Rottmayer
⠏ Downloading...Error: Input stream error: Error parsing info: Unable to retrieve video metadata
    at PassThrough.<anonymous> (/usr/local/lib/node_modules/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:452:34)
    at PassThrough.emit (events.js:315:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```
I'm running Fedora 33. 

I would think this is just a me problem, but since more people seem to have the same problem maybe it's a real issue so i'll try to do my part.

**Comment by pascal48** [comment]
I can also replicate, I have ffmpeg-4.3.1-11 installed.
 
 Download source: https://open.spotify.com/track/2CZnuQBGvGryfY2hDAzH8x?si=fmgCVHDCS9KmmtjPZyzxzg
 
 Output:
 
 ```
 ℹ Saving Song to: /home/#name/Downloads/Detached - Emil Rottmayer.mp3
 ✔ Song: Detached - Emil Rottmayer
 ⠏ Downloading...Error: Input stream error: Error parsing info: Unable to retrieve video metadata
     at PassThrough.<anonymous> (/usr/local/lib/node_modules/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:452:34)
     at PassThrough.emit (events.js:315:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 ```
  I'm running Fedora 33.

I would think this is just a me problem, but since more people seem to have the same problem maybe it's a real issue so i'll try to do my part.

**Comment by mrbooshehri** [comment]
I also faced with this problem too
I'm runing ubuntu 20.04 LTS and ffmpeg 4.2.4


Saving Song to: /home/mhmd/Pier - Slo Loris.mp3
✔ Song: Pier - Slo Loris
⠴ Downloading...Error: Input stream error: Error parsing info: Unable to retrieve video metadata
    at PassThrough.<anonymous> (/home/mhmd/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:452:34)
    at PassThrough.emit (events.js:198:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by barbariandub** [comment]
Unfortunately, I am having the same issue. 

```C:\Users\alper\OneDrive\Desktop\spotify download>spotifydl https://open.spotify.com/playlist/2blfWNQQYW2vgZLV8VmiBn
i Total Songs: 119
i Saving Playlist: C:\Users\alper\OneDrive\Desktop\spotify download\Türkçe Rap Zirvedekiler ⛰️ - ⭐️ Koray
i 1. Song: Bırakman Doğru Mu 2 - Zeynep Bastık
/ Downloading...Error: Input stream error: Error parsing info: Unable to retrieve video metadata
    at PassThrough.<anonymous> (C:\Users\alper\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:452:34)
    at PassThrough.emit (node:events:376:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

C:\Users\alper\OneDrive\Desktop\spotify download>spotifydl https://open.spotify.com/playlist/2blfWNQQYW2vgZLV8VmiBn
i Total Songs: 119
i Saving Playlist: C:\Users\alper\OneDrive\Desktop\spotify download\Türkçe Rap Zirvedekiler ⛰️ - ⭐️ Koray
i 1. Song: Bırakman Doğru Mu 2 - Zeynep Bastık
| Downloading...Error: Input stream error: Error parsing info: Unable to retrieve video metadata
    at PassThrough.<anonymous> (C:\Users\alper\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:452:34)
    at PassThrough.emit (node:events:376:20)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)```

**Comment by Inf3xt** [comment]
Also having this issue

```D:\Test>spotifydl https://open.spotify.com/track/2TgDK4TC5KsywTYafAE4Gd
i Saving Song to: D:\Test\Imaginary - Brennan Heart.mp3
√ Song: Imaginary - Brennan Heart
| Downloading...Error: Input stream error: Error parsing info: Unable to retrieve video metadata
    at PassThrough.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:452:34)
    at PassThrough.emit (events.js:315:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by DavidGriffith** [comment]
Running Debian 10 with FFMPEG 10:4.1.6-dmo1+deb10u1 installed through APT.

````
linux:~/foo$ spotifydl https://open.spotify.com/track/5KYoPa5akZxiCn38xelbqI
ℹ Saving Song to: /home/bob/foo/Manic Monday - The Bangles.mp3
✔ Song: Manic Monday - The Bangles
⠸ Downloading...Error: Input stream error: Error parsing info: Unable to retrieve video metadata
    at PassThrough.<anonymous> (/home/bob/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:452:34)
    at PassThrough.emit (events.js:198:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
````

**Comment by SwapnilSoni1999** [comment]
please checkout v0.4.7 and close the issue if solved. 
Thanks

**Comment by mrbooshehri** [comment]
> please checkout v0.4.7 and close the issue if solved.
> Thanks

It properly works, thanks.
