### ISSUE TITLE
Invalid Argument error when downloading album

### ISSUE THREAD

**Issue by severien** [SwapnilSoni1999/spotify-dl#64]
When trying to download an album the application crashes with `Invalid Argument`

```
spotifydl https://open.spotify.com/album/xyz                                                                                                                                           
ℹ Total Songs: 4
ℹ Saving Album: /Users/someuser/Music/Album Name
ℹ 1. Song: First song
⠸ Downloading...events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: /Users/someuser/Music/Album Name: Invalid argument

    at ChildProcess.<anonymous> (/Users/someuser/.nvm/versions/node/v12.13.1/lib/node_modules/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (/Users/someuser/.nvm/versions/node/v12.13.1/lib/node_modules/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at endCB (/Users/someuser/.nvm/versions/node/v12.13.1/lib/node_modules/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:544:13)
    at handleExit (/Users/someuser/.nvm/versions/node/v12.13.1/lib/node_modules/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:170:11)
    at ChildProcess.<anonymous> (/Users/someuser/.nvm/versions/node/v12.13.1/lib/node_modules/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:182:11)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by HAUDRAUFHAUN** [comment]
I have the same error

**Comment by misterboe** [comment]
This could be fixed by remove Line 21 from lib/downloader.js

https://github.com/SwapnilSoni1999/spotify-dl/blob/1f3d8a15f3342d690c4290e1bcbb62d73909269b/lib/downloader.js#L21

**Comment by misterboe** [comment]
It seems like there are problems with the album names. If you put the album in a playlist the download works for me

**Comment by Impr0ve** [comment]
adding the album to the playlist works but is there a way that the track numbers also get into the metadata that would be cool also whats the proper way to update the ytdl-core

**Comment by misterboe** [comment]
Thats the Link i tried btw. 
`https://open.spotify.com/album/39QjW5XIE81HsWRjjyaVH0?si=A_8zL3BbQteQTQVlZM-Szw`

**Comment by HAUDRAUFHAUN** [comment]
> It seems like there are problems with the album names. If you put the album in a playlist the download works for me

Yes, it also thought this could be the problem because with single tracks it works

**Comment by severien** [comment]
The album metadata has the hashes of all the tracks. You could reuse the single track routine to download all the album tracks. Think its a matter of creating a folder with the album name and saving the tracks there.

**Comment by SwapnilSoni1999** [comment]
Can you please check if it works with latest version?

**Comment by HAUDRAUFHAUN** [comment]
I updatet to the lastest version (`npm i -g spotify-dl@latest`) but then I got this error:
```
✖ Something went wrong!
TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/spotify-dl/lib/api.js:94:44
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Spotifye.extrAlbum (/usr/local/lib/node_modules/spotify-dl/util/get-songdata.js:43:23)
    at async /usr/local/lib/node_modules/spotify-dl/cli.js:141:22
```

**Comment by SwapnilSoni1999** [comment]
I found out that album generation output was misplaced in an argument! I'm working on it.
