### ISSUE TITLE
Cannot download podcast episode because of "invalid URL type"

### ISSUE THREAD

**Issue by mpenkov** [SwapnilSoni1999/spotify-dl#66]
The URL looks valid: https://open.spotify.com/episode/2RYuGMhdQCk6FFoFJzKUR1?si=cDKxUAcaT-evvR6jJuXuJQ but I get this when I try to download it:

```
$ spotifydl "https://open.spotify.com/episode/2RYuGMhdQCk6FFoFJzKUR1?si=cDKxUAcaT-evvR6jJuXuJQ"
✖ Something went wrong!
Error: Invalid URL type
    at /usr/local/lib/node_modules/spotify-dl/cli.js:184:17
```

**Comment by mpenkov** [comment]
I had a peek at the source and tried to work around the problem by adding the episode to a playlist. Now I get a different error:

```
$ spotifydl "https://open.spotify.com/playlist/3luZ5mJbCTTBePUagnI4AK"
✖ Something went wrong!
TypeError: Cannot read property 'id' of null
    at /usr/local/lib/node_modules/spotify-dl/lib/api.js:75:52
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/spotify-dl/lib/api.js:74:40
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Spotifye.extrPlaylist (/usr/local/lib/node_modules/spotify-dl/util/get-songdata.js:39:23)
    at async /usr/local/lib/node_modules/spotify-dl/cli.js:103:22
```

**Comment by viewsourc3** [comment]
I don't know if this will help, but I also have the same issue. (running OSX Catalina)

```
Error: Invalid URL type
at /usr/local/lib/node_modules/spotify-dl/cli.js:184:17
at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by SwapnilSoni1999** [comment]
Sorry but podcasts download is not possible with this tool
