### ISSUE TITLE
Can't download album

### ISSUE THREAD

**Issue by SnwMds** [SwapnilSoni1999/spotify-dl#73]
Command:

```bash
$ mkdir -p ~/Music
$ cd ~/Music 
$ ~/node_modules/spotify-dl/cli.js 'https://open.spotify.com/album/0jNwqmKIwudqqbMJRRtzQb?si=okRWtt1MSbOdjSB8QvnLVQ'
```

Output:

```javascript
- Searching…
> Total Songs: 33
> Saving Album: /home/snwmds/Music/TV Anime "Attack on Titan Season 2" (Original Soundtrack) - PONY CANYON
> 1. Song: Barricades - Hiroyuki Sawano
- Downloading...
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: /home/snwmds/Music/TV Anime "Attack on Titan Season 2" (Original Soundtrack) - PONY CANYON/Barricades - Hiroyuki Sawano.mp3: No such file or directory

    at ChildProcess.<anonymous> (/home/snwmds/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
Emitted 'error' event on FfmpegCommand instance at:
    at emitEnd (/home/snwmds/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at endCB (/home/snwmds/node_modules/fluent-ffmpeg/lib/processor.js:544:13)
    at handleExit (/home/snwmds/node_modules/fluent-ffmpeg/lib/processor.js:170:11)
    at Socket.<anonymous> (/home/snwmds/node_modules/fluent-ffmpeg/lib/processor.js:209:9)
    at Socket.emit (events.js:323:22)
    at Pipe.<anonymous> (net.js:668:12)
```

**Comment by SwapnilSoni1999** [comment]
Thanks for letting know I'll fix this asap.
