### ISSUE TITLE
Error writing metadata after downloading a song

### ISSUE THREAD

**Issue by NathanielJS1541** [SwapnilSoni1999/spotify-dl#85]
I installed spotify-dl on termux using the setup script and it worked for a while, but recently I have been getting the same error about writing metadata, which means I can't download more than one song at a time as it throws this error after every song:
```js
ℹ Total Songs: 14
ℹ Saving Album: /data/data/com.termux/files/home/storage/shared/Music/Follow The Leader - Immortal-Epic
ℹ 1. Song: It's On! - Korn
⠋ Downloading...
 DIR: Follow The Leader - Immortal-Epic
✔ Download completed.
/data/data/com.termux/files/usr/lib/node_modules/spotify-dl/lib/metadata.js:33
                throw new Error('Error writing Metadata!',err);
                ^

Error: Error writing Metadata!
    at Stream.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/spotify-dl/lib/metadata.js:33:23)
    at Stream.emit (events.js:315:20)
    at /data/data/com.termux/files/usr/lib/node_modules/spotify-dl/node_modules/ffmetadata/index.js:100:11
    at FSReqCallback.oncomplete (fs.js:171:23)
Press any key to exit...
```

**Comment by phyzical** [comment]
just for replicating this could you please link the link that is throwing this?

**Comment by NathanielJS1541** [comment]
Closing this issue as I can't reproduce it anymore, I had tried everything I could think of and even tried reinstalling spotify-dl. However it seems to be fine now.
