### ISSUE TITLE
Bug : Command failed: where ffmpeg

### ISSUE THREAD

**Issue by lucasvieceli** [SwapnilSoni1999/spotify-dl#9]
Windows: 10 x64

```INFORMA��ES: n�o foi poss�vel localizar arquivos para o(s) padr�o(�es) especificado(s).
child_process.js:677
    throw err;
    ^

Error: Command failed: where ffmpeg
INFORMA��ES: n�o foi poss�vel localizar arquivos para o(s) padr�o(�es) especificado(s).

    at checkExecSyncError (child_process.js:637:11)
    at execSync (child_process.js:674:13)
    at Object.ffmpeg (C:\Users\DEV-01-PC\AppData\Roaming\npm\node_modules\spotify-dl\lib\setup.js:8:38)
    at Object.<anonymous> (C:\Users\DEV-01-PC\AppData\Roaming\npm\node_modules\spotify-dl\cli.js:16:7)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
PS F:\xampp\htdocs\lucas>```

**Comment by lucasvieceli** [comment]
CLOSED :D

**Comment by lucasvieceli** [comment]
```
Error: Input stream error: Status code: 403
    at PassThrough.<anonymous> (F:\xampp\htdocs\lucas\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:452:34)
    at PassThrough.emit (events.js:198:15)
    at PassThrough.req.prependListener (F:\xampp\htdocs\lucas\spotify-dl\node_modules\ytdl-core\lib\index.js:131:14)
    at PassThrough.emit (events.js:193:13)
    at ClientRequest.httpLib.get (F:\xampp\htdocs\lucas\spotify-dl\node_modules\miniget\lib\index.js:127:18)
    at Object.onceWrapper (events.js:281:20)
    at ClientRequest.emit (events.js:193:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:560:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
    at TLSSocket.socketOnData (_http_client.js:447:20)
Emitted 'error' event at:
    at emitEnd (F:\xampp\htdocs\lucas\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at PassThrough.<anonymous> (F:\xampp\htdocs\lucas\spotify-dl\node_modules\fluent-ffmpeg\lib\processor.js:454:15)
    at PassThrough.emit (events.js:198:15)
    [... lines matching original stack trace ...]
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)```

**Comment by gsdsd** [comment]
Please read **README.MD**.
And install FFMPEG -> [https://ffmpeg.zeranoe.com/builds/](https://ffmpeg.zeranoe.com/builds/)

**Comment by SwapnilSoni1999** [comment]
Install FFMPEG and set to environment variable.
